name: Report
description: Track operational reporting, audits, and analytics.
labels: ["report"]
assignees: []  # Top-level assignees if needed

body:
  # Report Name / Type
  - type: input
    id: report_name
    attributes:
      label: Report Name / Type
      placeholder: "Enter the name or type of the report"
    validations:
      required: true

  # Status
  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Not Started
        - In Progress
        - Draft Completed
        - Final Submitted
      description: "Select the current status of the report"
      default: 0
    validations:
      required: true

  # Reporting Period / Dates
  - type: input
    id: reporting_period
    attributes:
      label: Reporting Period / Dates
      description: "Enter the reporting period, e.g., 2026-01-01 to 2026-01-31"
      placeholder: "YYYY-MM-DD to YYYY-MM-DD"
    validations:
      required: true

  # Data Sources / Attachments
  - type: textarea
    id: data_sources
    attributes:
      label: Data Sources / Attachments
      placeholder: "Optional: List data sources or attach relevant files"
    validations:
      required: true

  # Key Findings / Observations
  - type: textarea
    id: key_findings
    attributes:
      label: Key Findings / Observations
      placeholder: "Summarise the main findings or observations from this report"
    validations:
      required: true

  # Recommendations / Next Steps
  - type: textarea
    id: recommendations
    attributes:
      label: Recommendations / Next Steps
      placeholder: "Optional: Recommended actions based on findings"
    validations:
      required: false

  # Other People to copy
  - type: textarea
    id: managers_to_notify
    attributes:
      label: Other People to copy
      description: "Add GitHub usernames to notify (use cc:@username, comma-separated)"
      placeholder: "cc:@manager1, @manager2"
    validations:
      required: false

  - type: textarea
    id: comment_template
    attributes:
      label: Copyable Comment Template (DO NOT EDIT!)
      description: "Copy and paste the following into a comment to update progress. Follow the instructions in each field."
      value: |
        ```markdown
        #### Update: 
        e.g., Acknowledgement, Draft completed, Final submitted
        
        **Status:** Choose one: Not Started / In Progress / Draft Completed / Final Submitted
        
        #### Key Findings / Observations: 
        e.g., Summarise the main points or insights
        
        #### Recommendations / Next Steps: 
        e.g., State next actions; Notify others if needed
        ```
    validations:
      required: false
