name: Task
description: Create a new task with ownership, deadline, and definition of done.
title: "[Task] "
labels: ["task"]
assignees: []  # Top-level assignees if needed

body:
  # Task Description
  - type: textarea
    id: task_description
    attributes:
      label: What needs to be done?
      placeholder: "Describe the task in detail"
    validations:
      required: true

  # Other People to copy
  - type: textarea
    id: managers_to_notify
    attributes:
      label:  Other People to cop
      description: "Add GitHub usernames to notify (use cc:@username, comma-separated) of task"
      placeholder: "cc:@manager1, @manager2"
    validations:
      required: false

  # Deadline
  - type: input
    id: deadline
    attributes:
      label: Deadline
      description: "YYYY-MM-DD"
      placeholder: "2026-02-15"
    validations:
      required: true

  # Priority
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
      description: "Select the priority of this task"
      default: 1  # 0-based index → "Medium"
    validations:
      required: true

  # Definition of Done
  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: "Describe how we know this task is complete."
      placeholder: "- Task completed and tested\n- Documentation updated\n- Stakeholders informed"
    validations:
      required: true

  # Copyable Comment Template
  - type: textarea
    id: comment_template
    attributes:
      label: Copyable Comment Template (DO NOT EDIT!)
      description: "Copy and paste the following into a comment to update progress."
      value: |
        ```markdown
        **Update:** [Brief update on progress]
        **Status:** Not Started / In Progress / Blocked / Done
        **Notes / Challenges:** [Optional]
        **Next Steps:** [Optional]
        ```
    validations:
      required: false
