name: Task Issue
about: Create a detailed task issue with instructions and comment templates
title: "[TASK] "
labels: task
assignees: ''

---

## Task Overview
**Title:**  
_Short descriptive title of the task_

**Description:**  
_Detail the task, including the goal, expected outcomes, and context._

**Priority:**  
- [ ] High  
- [ ] Medium  
- [ ] Low

**Due Date:**  
_YYYY-MM-DD_

**Task Owner / Assignee:**  
_@username_

**Related Issues / References:**  
_Link related issues, documents, or resources_

---

## Requirements / Checklist
- [ ] Define task objectives clearly
- [ ] Include necessary resources or links
- [ ] Add steps for execution
- [ ] List dependencies if any
- [ ] Identify stakeholders to notify
- [ ] Add labels and milestones

---

## Additional Notes
_Any extra information to help complete the task._

---

## Comment Templates (Copy & Paste in YAML)
> Use these templates when updating this task. Replace placeholders (`@username`, `YYYY-MM-DD`, `XX%`) as needed.

### **1. Task Started**
```yaml
body: |
  🔹 Task Update: Started
  Assigned to: @username
  Start Date: YYYY-MM-DD
  Notes: Task has officially started.
