name: Task Issue Form
title: "[TASK] "
labels: ["task"]
assignees: []

description: >
  Use this form to create a detailed task issue with all necessary information.
  At the end, copy comment templates for updates.

body:
  - type: input
    id: task_title
    attributes:
      label: "Task Title"
      description: "Short descriptive title for the task"
      placeholder: "Implement login feature"
      required: true

  - type: textarea
    id: task_description
    attributes:
      label: "Description"
      description: "Detail the task, including goals and expected outcomes"
      placeholder: "This task involves creating a login feature for the app..."
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "Select task priority"
      options:
        - High
        - Medium
        - Low
      required: true

  - type: input
    id: due_date
    attributes:
      label: "Due Date"
      description: "YYYY-MM-DD"
      placeholder: "2026-03-01"
      required: false

  - type: input
    id: assignee
    attributes:
      label: "Task Owner / Assignee"
      description: "GitHub username of the task owner"
      placeholder: "@username"
      required: false

  - type: textarea
    id: related_issues
    attributes:
      label: "Related Issues / References"
      description: "Link related issues or resources"
      placeholder: "https://github.com/org/repo/issues/123"
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Task Checklist"
      options:
        - Define task objectives clearly
        - Include necessary resources or links
        - Add steps for execution
        - List dependencies if any
        - Identify stakeholders to notify
        - Add labels and milestones

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes"
      description: "Any extra information to help complete the task"
      required: false

  - type: textarea
    id: comment_templates
    attributes:
      label: "Comment Templates (Copy & Paste YAML)"
      description: |
        Use these templates for updates. Replace placeholders like @username, YYYY-MM-DD, XX%.
      default: |
        ### Task Started
        ```yaml
        body: |
          🔹 Task Update: Started
          Assigned to: @username
          Start Date: YYYY-MM-DD
          Notes: Task has officially started.
        ```

        ### Task In Progress
        ```yaml
        body: |
          🔹 Task Update: In Progress
          Assigned to: @username
          Progress: XX%
          Notes: Current updates or blockers.
        ```

        ### Task Completed
        ```yaml
        body: |
          ✅ Task Update: Completed
          Completed by: @username
          Completion Date: YYYY-MM-DD
          Notes: Final remarks, outcomes, or follow-ups.
        ```

        ### Task Blocked / Needs Attention
        ```yaml
        body: |
          ⚠️ Task Update: Blocked
          Assigned to: @username
          Issue: Describe blocker
          Action Needed: Describe next steps or assistance required
        ```
